mode: "train"
algorithm: "NNR"
module: "CNN1D"
config_data_train: "data/train"
config_data_test: "data/test"
config_hyperparameters: "hyperparameters/dev_NNR"
config_module: "module/dev_CNN1D_regression"
output_path: "./dev/"
performance_intervals:
  - [0.5, 1]
  - [1, 3]
  - [3, 5]
  - [5, 10]
  - [10, 20]
  - [20, 30]
  - [30, 50]
  - [50, 70]
  - [70, 100]
  - [100, 150]
  - [150, 200]
  - [200, 300]
