data_paths_train:
  - data: ["EtOH_DB_V3_2_9499.csv", "EtOH_DB_V3_2_random.csv"]

chips_train: ["UUT1", "UUT2"]

gases_train: ["FinalConcEtOH"]

minibatch_size_train: 16
minibatch_step_train: 1

pre_processing_train:
  - name: "SkipData"
    percentage: 0
  - name: "LimitOfDetection"
    gases: ["FinalConcEtOH"]
    lod: [0.5]

transform_train:
  x:
    - name: "Transpose"
